[project]
name = "refiner"
version = "0.0.1"
authors = [
  { name="Alex Daro", email="alexdaro34@gmail.com" },
]
description = "A tool for refining AI datasets"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
refiner = "bin.cli:cli"

[project.urls]
"Homepage" = "https://github.com/adaro/ai-refiner"